### ISSUE TITLE
Live Acquisition Plot

### ISSUE THREAD

**Issue by jomy-kk** [scientisst/sense-web#10]
Live acquisition plots of the "active" channels.

- [x] Basic functionality
- [x] X-axis with relative time, rather than sample numbers
- [ ] Decimation according to screen resolution (?)
- [ ] Hide plots and show only current value

Let's leave performance tests for later. The goal is merely to put this to work.

**Comment by ruigouveiamaciel** [comment]
Moving the two incompleted tasks to their own separate issues
