### ISSUE TITLE
[BUG] SENSE Web not working in Chrome for Wi-Fi version

### ISSUE THREAD

**Issue by anascacais** [scientisst/sense-web#5]
**Describe the bug**
SENSE Web not working in Chrome for Wi-Fi version, due to certificate

**To Reproduce**
1. Go to sense web and choose wifi
2. Connect to ScientISST wifi
3. Click connect on sense.scientisst
4. See error [image]

**Expected behavior**
After attempting connection, a page should open so that I could "trust" connection.

**Screenshots**

<img width="874" alt="Screenshot 2022-10-18 at 11 17 46" src="https://user-images.githubusercontent.com/37815826/196407944-02db8491-aefd-4060-9293-e0d5ff9ac3ce.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12
 - Browser: Chrome 
 - Version: 106.0.5249.119 (Official Build) (arm64)

**Additional context**
Solved the issue by using Safari

**Comment by ruigouveiamaciel** [comment]
This is a security measure imposed by Chrome on MacOS and cannot be disabled. If you want to use Chrome and come across this screen you should type "thisisunsafe" on the screen and after some seconds it will load the intended page.

PS. There is no field to type "thisisunsafe". Just click on the screen and type it.
